### ISSUE TITLE
Are many mostly black screens on autostart/boot normal?

### ISSUE THREAD

**Issue by whiteenvelope** [TomWhitwell/SlowMovie#105]
**Describe the problem**
When doing commands by ssh everything seems to go perfectly, but rebooting the rpi to let the boot autostart begin Slowmovie seems to just create mostly black screens. I seem to be getting this screen or a very similar one basically constantly, I've let it run for about 20-30 minutes now but I'm not getting proper images yet.

**Platform Information** 
Raspberry pi 3b.  I saw in one instructable (https://www.instructables.com/Very-Slow-Movie-Player/) about doing this that they said "Beware, it usually starts with a bunch of all-black frames. "
So this might be normal? After a half hour or hour or so it just starts working? 
I have two mkv files in the video folder that work fine when manually sending commands via ssh. e.g. "python3 /home/pi/SlowMovie/slowmovie.py -r"

See the screen I'm constantly getting here:

![1636750922657](https://user-images.githubusercontent.com/45036680/141534538-d213a092-616d-4b27-b648-8bf2a6409a87.jpg)

I originally got some errors as someone else did who posted here, though doing the fix he later posted seemed to fix it all. I haven't seen any obvious error messages in the slowmovie.log either.

Thanks

Another example here:
![1636751859477](https://user-images.githubusercontent.com/45036680/141535716-51f5ef6c-1f60-474a-aab8-8d5c501f72fe.jpg)
:

**Comment by robweber** [comment]
There are a lot of variables at play here. I guess the main ones are 

* What is the video - is it like a regular full length movie? 
* What are your settings? Specifically the time between advancing and the number of frames to advance (`-d` and `-i`)

If it's a full length movie that you're starting from the beginning, with no `-s` argument, and your time between frames is long, plus a lower number increment; then yes that could be normal. Odds are it will take a bit to get through the "blank" part of the video. 

You did mention that when running it on the command line it "works fine". Does that mean it showed images as you'd expect? The `-r` arg will show random frames rather than from the start so it's still possible it's working as expected when starting from the beginning. A log dump after running for at least an hour is probably worth looking at to troubleshoot any further.

**Comment by whiteenvelope** [comment]
Hi, ah ok thanks so much, I realise now I was being a bit of an idiot - I forgot of course that the beginning of any movie is likely always many black frames, so because its just starting from the default settings right from the start it is just showing that black! So it was just me not reaising that at all. As you say yes the random frame function would almost always be pulling non black images from the middle of films yes, it was regular full length movies I was using yes. Thanks! So I just need to add the -r random frame function to the autorun feature. Thank you!

**Comment by TomWhitwell** [comment]
In my experience, most films start with a few seconds of black. The main reason for the -s argument was to start say 1000 frames (40 seconds) in

**Comment by MartinDude** [comment]
On a related note: I edit the movies with a movie editor to remove the uninteresting leading and trailing portions like those black frames, the sometimes endless logos, the endless end-of-movie credits, and so on. And while I am at it, I resize the output to match the resolution of the e-Paper screen I am using (800x480 in my case). This makes for a little less processing on the RaspberryPi Zero 2 I am using...

**Comment by whiteenvelope** [comment]
Thanks @MartinDude - yes good point I can see why that would help these issues. I've been enjoying this a lot now that it's finished and framed.
