### ISSUE TITLE
Static Path

### ISSUE THREAD

**Issue by ap0l0** [TomWhitwell/SlowMovie#135]
**Describe the problem**
The automated script is returning the following error:
fatal: could not create leading directories of '/home/pi/SlowMovie': Permission denied

Latest OS versions require you to create a user instead of using the default "pi". I reviewed the script and updated the following lines with correct path:
```
# set the local directory
LOCAL_DIR="/home/pi/$(basename $GIT_REPO)"

cd /home/pi/
```

I am not a coder so I can't improve code to change the splash screen options or make it dynamic.

**Steps to Reproduce**
Run main script

**Platform Information** 
Raspberrybi Zero W
Debian Bulleye

**Comment by robweber** [comment]
Thanks for pointing this out. I saw some news about the `pi` user account a while back but didn't think about it's impact to this script specifically. 

I'll get a PR going but the fix is pretty basic, just need to insert the actual username into that line:

```
LOCAL_DIR="/home/$USER/$(basename $GIT_REPO)"
```

There are some other locations where the home path is given as well that will need to be updated.
