### ISSUE TITLE
Video display inconsistency 

### ISSUE THREAD

**Issue by NickAnsy** [TomWhitwell/SlowMovie#15]
Hey guys, sick of me yet?
Well, what I thought was a screen issue seems to not be.
After going back through the code, speculating that it could be a formatting issue with the video, and trying to the original "test.mp4" I made a discovery.
The screen displays the "test.mp4" perfectly, however when a different movie file is played the streaks and misinformation on the screen reappears (see photos).
I've played with the dithering option and was unsuccessful with finding a solution.
I would like to know the "test.mp4" video specifications to try and recreate it with a different file.
Thanks guys.

- **Update** After letting "test.mp4" play until frame 19 the streaks came back. (see photo)
I'm ready to give up. 
![IMG_4991](https://user-images.githubusercontent.com/73515243/101209364-77b6ea00-3628-11eb-8a12-42f0aa786552.jpeg)

![IMG_4988](https://user-images.githubusercontent.com/73515243/101200168-c6f61e00-361a-11eb-97fb-78a331427307.jpeg)
![IMG_4981](https://user-images.githubusercontent.com/73515243/101200718-8ea30f80-361b-11eb-8071-df77d7ffc728.jpeg)

**Comment by scsibug** [comment]
If you display the same image twice in a row, does that clear things up?  I doubt this has anything to do with the movie file itself.

**Comment by NickAnsy** [comment]
Hey Greg, just had someone with the same problem respond. Seems to be an issue with the PIP, simple uninstall/reinstall fixes it.
About to see if that works. 
Thanks again!

Nick

**Comment by NickAnsy** [comment]
It looks like it fixed the problem i was having but now it has streaks in the top left portion of the screen.
![image](https://user-images.githubusercontent.com/73515243/101290668-a237ad00-37b8-11eb-8f4a-be174c962d30.jpeg)

**Comment by scsibug** [comment]
It may help to compare the exact BMP file that was sent to the device with a picture of the screen.  

I wonder if deliberately adding noise to the image might reduce the visibility of the streaking.  I have played quite a bit with reducing artifacts from previous images and speeding up image transitions -- but I have never seen streaking like that, so I don't have any good ideas.

If you display the same image multiple times, are the streaks the same, present but in different places, or eventually go away completely?

**Comment by NickAnsy** [comment]
I tired displaying the same image multiple times and I can’t tell if they’re in the same places but they are close.
Was thinking the same thing about the dithering. Maybe creating a bmp with more noise would help?



On Dec 6, 2020, at 11:51 AM, Greg Heartsfield <notifications@github.com> wrote:


It may help to compare the exact BMP file that was sent to the device with a picture of the screen.

I wonder if deliberately adding noise to the image might reduce the visibility of the streaking. I have played quite a bit with reducing artifacts from previous images and speeding up image transitions -- but I have never seen streaking like that, so I don't have any good ideas.

If you display the same image multiple times, are the streaks the same, present but in different places, or eventually go away completely?

**Comment by NickAnsy** [comment]
I also read about this happening to other people and it being an issue with the female GPIO on the hat.  They said if you connect directly to the pi with jumpers to the hat instead of the 40pin GPIO it works perfectly.  Im just not sure how to do that.



On Dec 6, 2020, at 11:51 AM, Greg Heartsfield <notifications@github.com> wrote:


It may help to compare the exact BMP file that was sent to the device with a picture of the screen.

I wonder if deliberately adding noise to the image might reduce the visibility of the streaking. I have played quite a bit with reducing artifacts from previous images and speeding up image transitions -- but I have never seen streaking like that, so I don't have any good ideas.

If you display the same image multiple times, are the streaks the same, present but in different places, or eventually go away completely?

**Comment by scsibug** [comment]
My displays came with a connector and individual cables, as an alternative to the HAT.  Basically, something like this: [jumper wires](https://www.digikey.com/en/products/detail/sparkfun-electronics/PRT-12796/5993861?utm_adgroup=Jumper%20Wire&utm_source=google&utm_medium=cpc&utm_campaign=Shopping_Prototyping%2C%20Fabrication%20Products_NEW&utm_term=&utm_content=Jumper%20Wire&gclid=CjwKCAiAn7L-BRBbEiwAl9UtkOTt_ZRYRi_5e--STyKN4c_0yQm3MVrUQy-mmF4iJHMwfqWGNSnIERoCBSUQAvD_BwE)

**Comment by NickAnsy** [comment]
Yes mine as well, i just don’t know what goes where. There’s a group of 16 pins (8x8) I just don’t know how to connect to the Rpi.


Nick Ansbaugh
Cell : (574) 217-6119
Email : Nansbaugh@gmail.com

**Comment by TomWhitwell** [comment]
Wanted to drop in what I've learned about streaks on screen: 
1. I've been using my panel since May, pretty much on 24/7 except when it was at the framer. 
1. I've definitely seen streaks - like the really bad streaks that @NickAnsy posted from Big Lebowski - during that time 
1. I'm currently running Alphaville on my player, and it looks very good - solid blacks and bright whites - so I have no reason to think the streaks represent permanent physical damage to the screen. 
1. I get slight ghosting when for example there is a big white circle in a black screen - particularly when looking at the screen off-axis. I *believe* this is a limitation of the screen.  
1. So... what causes the streaks / display artefacts? *I don't know*. 
1. For a while I was using a Pi Zero W, which worked but gave quite regular artefacts / issues - there was also a low-contrast issue where images were grey. When I went back to a Pi4 I got a better result. But I suspect that was to do with environments, rather than the processing power of Pi vs Zero. I'm intrigued by the comment where someone reinstalled ffmpeg and saw a big improvement. 
1. My hunch is that this isn't an electrical / connection issue, although I do wonder about power supplies. 
1. It would be simple to add a line - like at 176 in slowmovie.py - to save the images as bitmaps before they're displayed, to see what the screen is being asked to render. I haven't tried this. 
1. I don't have any expertise in packaging / installers / dependencies in Python - I wonder if there is a much better / more consistent way to deploy this - with consistent versions of ffmpeg and PIL and the python library and the waveshare drivers. If someone can do that, I'll definitely take the pull request.

**Comment by TomWhitwell** [comment]
OK, I did point 8 above: 
ssh into your pi, go to the slowmovie folder: 
Create a directory:
`mkdir grabs`
Edit slowmovie.py:
`nano slowmovie.py`
Scroll down to line 176. After this line: 
`    pil_im = pil_im.convert(mode='1',dither=Image.FLOYDSTEINBERG)`
add: 
`    pil_im.save("grabs/" + str(frame) +".bmp")`
And it will save each frame into that folder. You can retrieve the grabs with Filezilla

Seems to work.

**Comment by TomWhitwell** [comment]
Here's the bmp and a photo of the screen. 

One thing I noticed while taking the picture: During the screen refresh process, there is one phase (only lasts a moment) where the screen is very streaky. I wonder if the issue is somehow the refresh getting stuck at that point. 

![img](https://user-images.githubusercontent.com/1890544/101612931-18c7eb00-3a03-11eb-8d09-e1709554245f.jpg)

**Comment by NickAnsy** [comment]
So I found the problem, and solved it.  The epd.EPD_Sleep() is in the wrong place and doesn't actually put the board to sleep.  Keeping the current running to the screen the entire time the code is running and eventually ruining the screen.  Tested on multiple 12.48in screens and confirmed. 
What tipped me off about it was that it happens in the same place on different screens over the same amount of time.  Time.sleep() puts the code to sleep and epd.EPD.Sleep() puts the board to sleep. 
Picture now has no streaks, or misplaced blocks of pixels after running for two days. ![image](https://user-images.githubusercontent.com/73515243/101654729-aef51480-39f5-11eb-9400-c39911f19825.jpeg)

**Comment by NickAnsy** [comment]
The original code did not put the module to sleep which in turn never turned off the big inductor to make the high voltage to pulse the panel.  Leaving it on heats the display up and makes it perform in strange ways (shown above), ultimately ruining your 160 dollar e-paper screen.  If the display is unplugged and sits for a couple days, run the demo code from waveshare.  If the screen performs normally you should be fine.  I will attach a copy of the revised Slowmovie.py code, I have revised lines 177 and 205. After dealing with this problem for months, I am proud to be able to call this solved.
[slowmovie.py.zip](https://github.com/TomWhitwell/SlowMovie/files/5681534/slowmovie.py.zip)

**Comment by TomWhitwell** [comment]
I'm glad this is working for you. Sleep was commented out because of the various wake from sleep bugs in the epd drivers: 
https://github.com/waveshare/e-Paper/issues/32
https://github.com/waveshare/e-Paper/issues/36
https://github.com/waveshare/e-Paper/pull/65
It looks like a full fix is there in 65, I'll investigate
