### ISSUE TITLE
Display only shows random dots instead of image

### ISSUE THREAD

**Issue by soulseller79** [TomWhitwell/SlowMovie#19]
I've followed the tutorial from Tom and set everything up correctly, as far as I can tell. But when I run helloworld.py (or the examples from Waveshare) I only get random dots instead of an image on the display (see attached photo). There are no error messages from the script, and the display "refreshes" (turns completely black, then completely white) before again showing the random dots while the script says it's showing another frame...
 I've followed the wiki from waveshare as well, so all dependencies are up to date. I'm using a Pi 3 with Noobs
![IMG_20201130_090044175](https://user-images.githubusercontent.com/76487491/102906410-df689400-4474-11eb-91f2-9af700432bf5.jpg)
has anyone seen something similar? Any idea what the problem might be?
thanks,
Daniel

**Comment by micric** [comment]
I had something similar, and another problem where the screen would always show the same picture, even after clearing. I believe it's related to the fact that the hat won't fix very well on my Pi4. Make sure it's really well connected. Sometimes I attach it, and then it slowly moves off, so that some pins are not working

**Comment by missionfloyd** [comment]
I had this problem too, seemingly out of nowhere. Got it replaced and the new one worked.
