### ISSUE TITLE
module_exit() never reached

### ISSUE THREAD

**Issue by micric** [TomWhitwell/SlowMovie#21]
https://github.com/TomWhitwell/SlowMovie/blob/e64538c6deba8b89d1fff3e4661e74260d8f88f2/helloworld.py#L82

From my understanding, this line is never used. Wouldn't it be better to have the whole infinite loop inside a try/except block, calling sleep() and module_exit() inside except KeyboardInterrupt ?

**Comment by robweber** [comment]
You are correct this is never reached. In the "in progress" V2 branch the ```epd.sleep``` method is now implemented between updates but the exit code is still never executed. 

Rather than wrapping the whole thing in a try/execpt block a good way of handling this would be to implement a listener for ```signal.SIGTERM``` and ```signal.SIGINT```. These could then wrap up the program before exit gracefully. Several clones of this repo already do this. I believe there is PR to add this to an updated version as well.

**Comment by robweber** [comment]
Once merged the program should exit gracefully and not throw an error as described above.
