### ISSUE TITLE
test.mp4 is corrupted

### ISSUE THREAD

**Issue by qubist** [TomWhitwell/SlowMovie#34]
I think `test.mp4` is corrupted or something else is weird with the file. When I play it using QuickTime Player or VLC, I get to 2.5 seconds in and then playback stops but the progress indicator keeps going. The rest of the video is weirdly blank.

#### Playing
* Progress indicator keeps moving through end of the video
* Video image freezes on last valid frame (two cars in rear-view mirror)

#### Scrubbing
When scrubbing and I get past that last valid frame, the video appears completely black.

#### Playing
* Video ends and window closes when it reaches the same last frame

#### Scrubbing
* Scrubbing beyond the last valid frame just displays that last image (two cars in rear-view mirror)

### SlowMovie

I think if `slowmovie.py` tries to display a frame from beyond the end of the valid frames in `test.mp4`, it *refreshes and then shows the last image it displayed*. This means if I was playing `spiritedaway.mkv` and then I play `test.mp4` starting with frame 100 or so, I get a refresh and an image of a frame from Spirited Away.

Can anyone reproduce any of these behaviors? To fix it we can simply trim that extra part off, I think.

**Comment by robweber** [comment]
The current master branch does have this as it doesn't pull the fps value from the video value but instead hardcodes it. The end result is that if your video doesn't match the hardcoded frame rate exactly as you approach the end of a video you'll attempt to load frames past the actual end of the file. I've reproduced this a bunch. This is a fixed in various branches as well as some pending PRs. Should be fixed soon! 

Regarding the test file I've had no issues with it in testing with an e-ink display but haven't tried viewing in on a PC or anything before.

**Comment by qubist** [comment]
> Should be fixed soon!

Hope so! You got a minute to chat synchronously? Shoot me an email willharrisbraun@gmail.com
